name: workflow trigger

on:
  push:
    branches:
      - dev  # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Call NetSuite RESTlet
      uses: fjogeleit/http-request-action@v1
      with:
         url: 'https://tstdrv2690016.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=312&deploy=2         '
         method: 'POST'
         customHeaders: |
                {
                    "Authorization": "NLAuth nlauth_account=TSTDRV2690016, nlauth_consumerkey=a270197b0c1eeae74d6efab1966cfe4998c1d084de2ef02895ce8e5d3dfdb264, nlauth_consumersecret=CONSUMER_SECRET, nlauth_token=5df7042df38f9d6c57606bf386a83609e6016311f8c5112fded51e35a81122a6 , nlauth_tokensecret=5fdfefac9b9aa5ebd4257a968f4da136b2a0fd2580d279f55aaffa77ae65443a",
                    "Content-Type": "application/json"
                }
         data: '{"key_1": "value_1", "key_2": "value_2"}'
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install expect
      run: sudo apt-get install expect

    
    - name: JDK version
      run: java --version

    - name: Install SuiteCloud CLI
      run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

    - name: Install SuiteCloud Unit Testing Framework
      run: npm install @oracle/suitecloud-unit-testing --save-dev

    - name: SuiteCloud CLI Version
      run: suitecloud --version
    - name: SuiteCloud CLI Auth
      run:  suitecloud account:savetoken --authid myNetSuiteDevRole --tokenid 037ecadb88acae7dd7d6a44f3aaa6a6e2b621c55b8c4b5e799cd86ee0998f55a --tokensecret 97bf365026cc9366a7b28c96c558d2f44b6b4e23321c4b86c2750236407ba914 --account tstdrv2690016



    - name: SuiteCloud Command test
      run: suitecloud file:list --folder "/SuiteScripts"
        



    # Add additional steps as needed

