name: Label Triggered Workflow
on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ui'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute Job
        run: echo "Issue with specific label found!"
      - name: Create Asana Task
        run: |
          curl -X POST https://app.asana.com/api/1.0/tasks \
          -H "Authorization: Bearer 2/1205676102159508/1206210055893265:60f6668eb77a5796e95acf288f225e96" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"data": {"workspace": "1205676102159518", "name": "UI Updated from GitHub", "notes": "Issue URL: ${{ github.event.issue.html_url }} Issue Description: ${{ github.event.issue.body }}", "projects": ["1205676223874099"]}}'
        env:
          ASANA_PAT: 2/1205676102159508/1206210055893265:60f6668eb77a5796e95acf288f225e96

