name: Deploy NetSuite SuiteCloud Project

on:
  push:
    branches:
      - dev  # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: JDK version
      run: java --version

    - name: Install SuiteCloud CLI
      run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

    - name: Install SuiteCloud Unit Testing Framework
      run: npm install @oracle/suitecloud-unit-testing --save-dev

    - name: SuiteCloud CLI Version
      run: suitecloud --version
    - name: SuiteCloud CLI Auth
      run:  suitecloud account:setup -i



    - name: SuiteCloud Command test
      run: suitecloud file:list --folder "/SuiteScripts"
        



    # Add additional steps as needed
